# -*- coding: utf-8 -*-
"""Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDw3B2DcI-v_l7EcyDM3MUNd4rVlPpdO

# **Sentiment Analysis**

1. Importing **Libraries**
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense, Dropout
from sklearn.model_selection import train_test_split
from textblob import TextBlob
from sklearn.utils import resample
from sklearn.utils import resample

"""**Dataset From Kaggle**"""

# Load Dataset
dataset = pd.read_csv("TouristReview.csv")  # Update with the correct path if needed

# Drop missing values
dataset_cleaned = dataset[['review']].dropna()

"""**Polarity for sentiment analysis prediction**"""

# Convert reviews to sentiment polarity (0 = Negative, 1 = Neutral, 2 = Positive)
def get_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity > 0:
        return 2  # Positive
    elif polarity < 0:
        return 0  # Negative
    else:
        return 1  # Neutral

dataset_cleaned['sentiment'] = dataset_cleaned['review'].apply(get_sentiment)

"""I have found that the dataset is imbalanced"""

# Class distribution before balancing
print("Before Balancing:")
print(dataset_cleaned['sentiment'].value_counts())

"""Downsampling - Oversampling for balanced dataset"""

# Separate classes
positive_reviews = dataset_cleaned[dataset_cleaned['sentiment'] == 2]  # Most frequent class
neutral_reviews = dataset_cleaned[dataset_cleaned['sentiment'] == 1]
negative_reviews = dataset_cleaned[dataset_cleaned['sentiment'] == 0]

# Undersample Positive class to match Neutral class count (1074)
positive_downsampled = resample(positive_reviews, replace=False, n_samples=len(neutral_reviews), random_state=42)

# Oversample Negative class to match 1074 samples
negative_oversampled = resample(negative_reviews, replace=True, n_samples=len(neutral_reviews), random_state=42)

# Combine the new balanced dataset
balanced_dataset = pd.concat([positive_downsampled, neutral_reviews, negative_oversampled])

# Shuffle dataset
balanced_dataset = balanced_dataset.sample(frac=1, random_state=42)

# Check new distribution
print("After Balancing:")
print(balanced_dataset['sentiment'].value_counts())

"""**Tokenization and Text Preprocessing**"""

# Tokenization and Text Preprocessing
max_words = 5000  # Maximum words in vocabulary
max_length = 100  # Max review length for padding
tokenizer = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokenizer.fit_on_texts(balanced_dataset['review'])
sequences = tokenizer.texts_to_sequences(balanced_dataset['review'])

"""**Pad Sequences**"""

# Pad sequences
X = pad_sequences(sequences, maxlen=max_length, padding='post', truncating='post')
y = np.array(balanced_dataset['sentiment'])

"""**Split DATA**"""

# Split Data (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""**CNN MODEL**"""

# Build CNN Model
model = Sequential([
    Embedding(input_dim=max_words, output_dim=128, input_length=max_length),
    Conv1D(128, 5, activation='relu'),  # Increased filters
    Dropout(0.4),  # Added dropout to prevent overfitting
    GlobalMaxPooling1D(),
    Dense(128, activation='relu'),
    Dropout(0.4),
    Dense(3, activation='softmax')  # 3 classes: Negative, Neutral, Positive
])

# Compile Model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train Model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

model.summary()

# Evaluate Model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

# Save Model
model.save("sentiment_analysis_cnn.h5")

"""# Test Cases"""

# Function to Predict Sentiment
def predict_sentiment(review):
    sequence = tokenizer.texts_to_sequences([review])
    padded = pad_sequences(sequence, maxlen=max_length, padding='post', truncating='post')
    prediction = model.predict(padded)
    sentiment_labels = ["Negative", "Neutral", "Positive"]  # Corrected Order
    return sentiment_labels[np.argmax(prediction)]

# Example Predictions:
print(predict_sentiment("The place was beautiful and amazing!"))  # Expected: Positive
print(predict_sentiment("Worst experience ever, not recommended."))  # Expected: Negative

print(predict_sentiment("It was an okay experience, nothing special."))

print(predict_sentiment("It is very bad"))

print(predict_sentiment("The best place I have been to"))